name: cem_occ
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - numpy
  - scipy
  - matplotlib
  - pandas
  - pythonocc-core=7.9.0
  - pyside6
  - pyvista
  - pyvistaqt
  - pip
  - pip:
      - geomdl
